### ISSUE TITLE
PP uses an invalid jarfile name

### ISSUE THREAD

**Issue by Crab55e** [flytegg/plugin-portal#16]
### Minified log

```
[23:24:24 INFO]: <ME> issued server command: /pluginportal install spigotmc:ImageFrameLoadImagesonMapsItemFramesSupportGIFsMapMarkersSurvivalFriendly
[23:24:28 WARN]: java.io.FileNotFoundException: plugins\ImageFrame | Load Images on Maps & Item Frames! | Support GIFs! | Map Markers! | Survival Friendly-510966 (PP).jar (ファイル名、ディレクトリ名、またはボリューム ラベルの構文が間違っています。)
```

### Full error log
<details>

<summary>Open</summary>

```
[23:24:24] [Server thread/INFO]: <ME> issued server command: /pluginportal install spigotmc:ImageFrameLoadImagesonMapsItemFramesSupportGIFsMapMarkersSurvivalFriendly
[23:24:28] [Craft Scheduler Thread - 42 - PluginPortal/WARN]: java.io.FileNotFoundException: plugins\ImageFrame | Load Images on Maps & Item Frames! | Support GIFs! | Map Markers! | Survival Friendly-510966 (PP).jar (ファイル名、ディレクトリ名、またはボリューム ラベルの構文が間違っています。)
[23:24:28] [Craft Scheduler Thread - 42 - PluginPortal/WARN]: 	at java.base/java.io.FileOutputStream.open0(Native Method)
[23:24:28] [Craft Scheduler Thread - 42 - PluginPortal/WARN]: 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
[23:24:28] [Craft Scheduler Thread - 42 - PluginPortal/WARN]: 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
[23:24:28] [Craft Scheduler Thread - 42 - PluginPortal/WARN]: 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
[23:24:28] [Craft Scheduler Thread - 42 - PluginPortal/WARN]: 	at PluginPortal-1.5.0.jar//link.portalbox.pplib.util.FileKt.download(File.kt:54)
[23:24:28] [Craft Scheduler Thread - 42 - PluginPortal/WARN]: 	at PluginPortal-1.5.0.jar//link.portalbox.pluginportal.util.PluginHandlerKt.install(PluginHandler.kt:42)
[23:24:28] [Craft Scheduler Thread - 42 - PluginPortal/WARN]: 	at PluginPortal-1.5.0.jar//link.portalbox.pluginportal.util.PluginHandlerKt.install(PluginHandler.kt:37)
[23:24:28] [Craft Scheduler Thread - 42 - PluginPortal/WARN]: 	at PluginPortal-1.5.0.jar//link.portalbox.pluginportal.command.sub.InstallSubCommand.execute$lambda$1(InstallSubCommand.kt:67)
[23:24:28] [Craft Scheduler Thread - 42 - PluginPortal/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:24:28] [Craft Scheduler Thread - 42 - PluginPortal/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:24:28] [Craft Scheduler Thread - 42 - PluginPortal/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:24:28] [Craft Scheduler Thread - 42 - PluginPortal/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:24:28] [Craft Scheduler Thread - 42 - PluginPortal/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:24:28] [Craft Scheduler Thread - 42 - PluginPortal/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23:24:28] [Craft Scheduler Thread - 42 - PluginPortal/WARN]: [PluginPortal] Plugin PluginPortal v1.5.0 generated an exception while executing task 135
java.io.FileNotFoundException: plugins\ImageFrame | Load Images on Maps & Item Frames! | Support GIFs! | Map Markers! | Survival Friendly-510966 (PP).jar (ファイル名、ディレクトリ名、またはボリューム ラベルの構文が間違っています。)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:216) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
	at link.portalbox.pluginportal.util.ToolKt.getSHA(Tool.kt:21) ~[PluginPortal-1.5.0.jar:?]
	at link.portalbox.pluginportal.util.PluginHandlerKt.install(PluginHandler.kt:54) ~[PluginPortal-1.5.0.jar:?]
	at link.portalbox.pluginportal.util.PluginHandlerKt.install(PluginHandler.kt:37) ~[PluginPortal-1.5.0.jar:?]
	at link.portalbox.pluginportal.command.sub.InstallSubCommand.execute$lambda$1(InstallSubCommand.kt:67) ~[PluginPortal-1.5.0.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-95]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-95]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

</details>

### Installed server
- Plugin Portal 1.5.0
- Paper 1.20.1 (build 95)
- Windows 11 Home

### Installed plugins
<details>

<summary>Open</summary>

- AntiPopup
- ArmorStandEditor
- BlueMap
- Chunky
- ChunkyBorder
- CommandSpy
- CoreProtect
- DiscordSRV
- DrMap
- GSit
- InventoryRollbackPlus
- LuckPerms
- LunaChat
- LWC
- mcMMO
- NickNames
- OpenInv
- Plan
- PluginPortal
- ProtocolLib
- ServerBackup
- ServerTap
- Skript
- spark
- SuperVanish
- TabTPS
- WorldEdit
- WorldGuard

</details>

**Comment by Dawsson** [comment]
Fixed, thank you
