### ISSUE TITLE
Plugin doesn't work properly

### ISSUE THREAD

**Issue by OPADILOP** [flytegg/plugin-portal#38]
### `/viaversion dump` Output

https://dump.viaversion.com/941d52de173c3e172eb22580b72de4f27d28673f60d65ad3a84cd10c501916ba

### Console Error

[20:17:53 INFO]: [PluginPortal] Enabling PluginPortal v1.5.0
[20:17:56 ERROR]: Error occurred while enabling PluginPortal v1.5.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'com.google.gson.JsonElement com.google.gson.JsonParser.parseString(java.lang.String)'
	at link.portalbox.pplib.util.HTTPKt.getJSONFromURL(HTTP.kt:21) ~[?:?]
	at link.portalbox.pplib.util.APIKt.getPPVersions(API.kt:49) ~[?:?]
	at link.portalbox.pplib.util.APIKt.getLatestPPVersion(API.kt:24) ~[?:?]
	at link.portalbox.pplib.util.APIKt.getLatestVersion(API.kt:28) ~[?:?]
	at link.portalbox.pluginportal.type.Data.init(Data.kt:54) ~[?:?]
	at link.portalbox.pluginportal.PluginPortal.onEnable(PluginPortal.kt:24) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[20:17:56 INFO]: [PluginPortal] Disabling PluginPortal v1.5.0

### Bug Description

Plugin doesn't run cause of some kind of gson error

### Steps to Reproduce

Plugin doesn't run...

### Expected Behavior

Plugin Should Run

### Additional Server Info

None

### Checklist

- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.

**Comment by Dawsson** [comment]
Thank you, and thank you for putting up with the viaversion template lmao.

Fixed in latest version
