### ISSUE TITLE
Error when plugin is starting!

### ISSUE THREAD

**Issue by Nerd10000** [flytegg/plugin-portal#41]
### `/viaversion dump` Output

https://dump.viaversion.com/3881b927ab5b5ce584cdca634202edf9fb935c00d4ebd5045e0a3cf3d64287ec

### Console Error

```
(https://hangar.papermc.io/Flyte/PluginPortal)
```

### Bug Description

Starting error.

### Steps to Reproduce

Yust start te sherver 

### Expected Behavior

Start the server

### Additional Server Info

Here is the error: [19:25:43 ERROR]: Error occurred while enabling PluginPortal v1.5.0 (Is it up to date?)
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8 path $
        at com.google.gson.JsonParser.parseReader(JsonParser.java:76) ~[gson-2.10.jar:?]
        at com.google.gson.JsonParser.parseString(JsonParser.java:51) ~[gson-2.10.jar:?]
        at link.portalbox.pplib.util.HTTPKt.getJSONFromURL(HTTP.kt:21) ~[PluginPortal-1.5.0.jar:?]
        at link.portalbox.pplib.util.APIKt.getPPVersions(API.kt:49) ~[PluginPortal-1.5.0.jar:?]
        at link.portalbox.pplib.util.APIKt.getLatestPPVersion(API.kt:24) ~[PluginPortal-1.5.0.jar:?]
        at link.portalbox.pplib.util.APIKt.getLatestVersion(API.kt:28) ~[PluginPortal-1.5.0.jar:?]
        at link.portalbox.pluginportal.type.Data.init(Data.kt:54) ~[PluginPortal-1.5.0.jar:?]
        at link.portalbox.pluginportal.PluginPortal.onEnable(PluginPortal.kt:24) ~[PluginPortal-1.5.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar:?]
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1463) ~[gson-2.10.jar:?]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551) ~[gson-2.10.jar:?]
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.jar:?]
        at com.google.gson.JsonParser.parseReader(JsonParser.java:71) ~[gson-2.10.jar:?]
        ... 19 more

### Checklist

- [ ] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [x] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [ ] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Dawsson** [comment]
Try now!

**Comment by Dawsson** [comment]
Fixed
