### ISSUE TITLE
CoreProtect is corrupted

### ISSUE THREAD

**Issue by LiteApplication** [flytegg/plugin-portal#45]
Steps to reproduce : 
 - Use HANGAR as the provider
 - `/pp install hangar:CoreProtect`

```traceback
org.bukkit.plugin.InvalidPluginException: java.lang.RuntimeException: File 'plugins/CoreProtect-22.4 (PP).jar' failed to update!
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:112) ~[paper-1.21.jar:1.21-15-2df432f]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.loadPlugin(PaperPluginManagerImpl.java:82) ~[paper-1.21.jar:1.21-15-2df432f]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:419) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at PluginPortal-1.5.0.jar/link.portalbox.pluginportal.util.PluginHandlerKt.install(PluginHandler.kt:57) ~[PluginPortal-1.5.0.jar:?]
        at PluginPortal-1.5.0.jar/link.portalbox.pluginportal.util.PluginHandlerKt.install(PluginHandler.kt:37) ~[PluginPortal-1.5.0.jar:?]
        at PluginPortal-1.5.0.jar/link.portalbox.pluginportal.command.sub.InstallSubCommand.execute$lambda$1(InstallSubCommand.kt:67) ~[PluginPortal-1.5.0.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.21.jar:1.21-15-2df432f]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.jar:1.21-15-2df432f]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.RuntimeException: File 'plugins/CoreProtect-22.4 (PP).jar' failed to update!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:57) ~[paper-1.21.jar:1.21-15-2df432f]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:105) ~[paper-1.21.jar:1.21-15-2df432f]
        ... 11 more
Caused by: org.bukkit.plugin.InvalidPluginException: java.util.zip.ZipException: zip END header not found
        at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:120) ~[paper-1.21.jar:1.21-15-2df432f]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:55) ~[paper-1.21.jar:1.21-15-2df432f]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:105) ~[paper-1.21.jar:1.21-15-2df432f]
        ... 11 more
Caused by: java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.findEND(Unknown Source) ~[?:?]
        at java.base/java.util.zip.ZipFile$Source.initCEN(Unknown Source) ~[?:?]
        at java.base/java.util.zip.ZipFile$Source.<init>(Unknown Source) ~[?:?]
        at java.base/java.util.zip.ZipFile$Source.get(Unknown Source) ~[?:?]
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source) ~[?:?]
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source) ~[?:?]
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source) ~[?:?]
        at java.base/java.util.jar.JarFile.<init>(Unknown Source) ~[?:?]
        at java.base/java.util.jar.JarFile.<init>(Unknown Source) ~[?:?]
        at java.base/java.util.jar.JarFile.<init>(Unknown Source) ~[?:?]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.getPluginName(FileProviderSource.java:126) ~[paper-1.21.jar:1.21-15-2df432f]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:101) ~[paper-1.21.jar:1.21-15-2df432f]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:55) ~[paper-1.21.jar:1.21-15-2df432f]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:105) ~[paper-1.21.jar:1.21-15-2df432f]
        ... 11 more
```

This message appears when starting the plugin (both on server start and with `startup-on-install: true`)

This does not happen with other HANGAR plugins.

Running `java -jar CoreProtect-22.4\ \(PP\).jar` prints the following message : 
```
Error: Invalid or corrupt jarfile CoreProtect-22.4 (PP).jar
```

**Comment by Dawsson** [comment]
Fixed. Will be released within a couple of days (2.0.0 release).
